import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useAuth } from '@/hooks/use-auth'
import { useTasks } from '@/hooks/use-tasks'
import { createTask, moveTask } from '@/services/task.service'
import { TASK_STATUSES, type TaskStatus } from '@/types/task'
function signal(date?: { toDate(): Date }) { if (!date) return 'bg-slate-300'; const days = Math.ceil((date.toDate().getTime() - Date.now()) / 86400000); return days <= 0 ? 'bg-red-500' : days <= 5 ? 'bg-amber-400' : 'bg-emerald-500' }
export function AgendaPage() { const { user, profile } = useAuth(); const client = useQueryClient(); const { data = [] } = useTasks(); const [title, setTitle] = useState(''); const mutation = useMutation({ mutationFn: () => createTask({ titulo: title, prioridad: 'Media', estado: 'Pendientes', responsableId: user!.uid, responsable: profile?.nombreCompleto ?? '', checklist: [] }), onSuccess: () => { setTitle(''); return client.invalidateQueries({ queryKey: ['tasks'] }) } }); const move = useMutation({ mutationFn: ({ id, status }: { id: string; status: TaskStatus }) => moveTask(id, status), onSuccess: () => client.invalidateQueries({ queryKey: ['tasks'] }) }); return <section className="mx-auto max-w-7xl space-y-5"><div className="flex justify-between"><div><p className="text-sm font-medium text-primary">Organización personal</p><h1 className="text-2xl font-semibold">Mi Agenda</h1></div><div className="flex gap-2"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Nueva tarea"/><Button disabled={!title.trim()} onClick={() => mutation.mutate()}>Crear tarea</Button></div></div><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{[['Total', data.length], ...TASK_STATUSES.map((status) => [status, data.filter((task) => task.estado === status).length])].map(([label, value]) => <Card key={String(label)} className="p-3"><p className="text-xs text-slate-500">{label}</p><b className="text-xl">{value}</b></Card>)}</div><div className="grid gap-4 lg:grid-cols-4">{TASK_STATUSES.map((status) => <Card key={status} className="min-h-64 bg-slate-50 p-3" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData('text/task'); if (id) move.mutate({ id, status }) }}><h2 className="mb-3 font-semibold">{status}</h2>{data.filter((task) => task.estado === status).map((task) => <article key={task.id} draggable onDragStart={(event) => event.dataTransfer.setData('text/task', task.id)} className="mb-3 cursor-grab rounded-lg border bg-white p-3 shadow-sm"><div className="flex justify-between"><b className="text-sm">{task.titulo}</b><span className={`size-3 rounded-full ${signal(task.fechaLimite)}`}/></div><Badge className="mt-2" variant={task.prioridad === 'Alta' ? 'destructive' : 'default'}>{task.prioridad}</Badge>{task.expedienteRadicado && <p className="mt-2 text-xs text-primary">Exp. {task.expedienteRadicado}</p>}</article>)}</Card>)}</div></section> }
