import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Check, FileText, Settings2 } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Select } from '@/components/ui/select'
import { useAuth } from '@/hooks/use-auth'
import { useAssignableOfficials } from '@/hooks/use-assignable-officials'
import { useExpedientDetail, useExpedientHistory } from '@/hooks/use-expedient-detail'
import { transferByCompetence, updateExpedientAssignee, updateExpedientPriority, updateExpedientStatus, updateExternalAssignee } from '@/services/expedient.service'
import { isFinalizedExpedient, STANDARD_FLOW, TRANSFER_FLOW, type ExpedientPriority } from '@/types/expedient'

type Tab = 'Información' | 'Acciones' | 'Historial' | 'Documentos'
const tabs: Tab[] = ['Información', 'Acciones', 'Historial', 'Documentos']

export function ExpedientDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const client = useQueryClient(); const { data: item, isLoading } = useExpedientDetail(id); const { data: history = [] } = useExpedientHistory(id); const { data: officials = [] } = useAssignableOfficials()
  const [tab, setTab] = useState<Tab>('Información'); const [mode, setMode] = useState<'team' | 'other'>('team'); const [official, setOfficial] = useState(''); const [external, setExternal] = useState(''); const [destination, setDestination] = useState('')
  const refresh = () => Promise.all(['expedient', 'expedient-history', 'expedients', 'work-tray', 'historical-expedients'].map((key) => client.invalidateQueries({ queryKey: [key, key === 'expedient' || key === 'expedient-history' ? id : undefined] })))
  const flow = item?.trasladoPorCompetencia ? TRANSFER_FLOW : STANDARD_FLOW
  const status = useMutation({ mutationFn: (value: typeof flow[number]) => updateExpedientStatus(id!, value, user!.uid, flow), onSuccess: refresh })
  const assignee = useMutation({ mutationFn: () => mode === 'team' ? (() => { const value = officials.find((entry) => entry.uid === official); return updateExpedientAssignee(id!, value ? { uid: value.uid, nombreCompleto: value.nombreCompleto } : undefined, user!.uid) })() : updateExternalAssignee(id!, external, user!.uid), onSuccess: refresh })
  const priority = useMutation({ mutationFn: (value: ExpedientPriority | undefined) => updateExpedientPriority(id!, value, user!.uid), onSuccess: refresh })
  const transfer = useMutation({ mutationFn: () => transferByCompetence(id!, destination, user!.uid), onSuccess: refresh })
  if (isLoading) return <p className="text-sm text-slate-500">Cargando expediente…</p>
  if (!item) return <p className="text-sm text-slate-500">No se encontró el expediente.</p>
  const finalized = isFinalizedExpedient(item); const current = Math.max(0, flow.indexOf(item.estado))
  return <section className="mx-auto max-w-7xl space-y-5"><div className="flex justify-between"><div><Link to={finalized ? '/historico' : '/dashboard'} className="text-sm text-slate-500">← Volver</Link><p className="mt-3 text-sm font-medium text-primary">Expediente {item.numeroRadicado}</p><h1 className="text-2xl font-semibold">Gestión del trámite</h1></div><Badge variant={finalized ? 'success' : 'info'}>{finalized ? 'Solo consulta' : item.estado}</Badge></div>
    <Card className="overflow-x-auto p-4"><div className="flex min-w-[700px] gap-2">{flow.map((value, index) => <div key={value} className="flex flex-1 items-center gap-2"><button type="button" disabled={finalized || status.isPending || Math.abs(index - current) > 1} onClick={() => status.mutate(value)} className={`w-full rounded-lg border p-3 text-left ${index === current ? 'border-primary bg-primary text-primary-foreground' : index < current ? 'border-emerald-200 bg-emerald-50' : 'disabled:opacity-50'}`}><span className="block text-xs">{index < current ? <Check size={14}/> : index + 1}</span><b className="text-sm">{value}</b><small className="mt-1 block">{index === current ? 'Actual' : index === current + 1 ? 'Siguiente paso' : 'Paso del flujo'}</small></button>{index < flow.length - 1 && <span>→</span>}</div>)}</div></Card>
    <div className="flex gap-1 border-b">{tabs.map((value) => <button key={value} onClick={() => setTab(value)} className={`border-b-2 px-4 py-3 text-sm ${tab === value ? 'border-primary text-primary' : 'border-transparent text-slate-500'}`}>{value}</button>)}</div>
    <Card className="p-5">{tab === 'Información' && <div className="grid gap-5 md:grid-cols-2"><div><h2 className="font-semibold">Información del expediente</h2><p className="mt-3 text-sm">Tipo: {item.tipoTramite ?? 'Sin configurar'}</p><p className="text-sm">Radicado: {item.fechaRadicado.toDate().toLocaleDateString('es-CO')}</p><p className="text-sm">Solicitante: {item.solicitantes[0]?.nombre ?? '—'}</p><p className="text-sm">Municipio: {item.predios[0]?.municipio ?? '—'}</p></div><div><h2 className="font-semibold">Resumen</h2><p className="mt-3 text-sm text-slate-600">{item.observacionesIniciales ?? 'Sin observaciones iniciales.'}</p></div></div>}
      {tab === 'Acciones' && (finalized ? <p className="text-sm text-slate-500">Los expedientes finalizados no admiten modificaciones.</p> : <div className="grid gap-6 lg:grid-cols-3"><div><h2 className="flex items-center gap-2 font-semibold"><Settings2 size={17}/> Cambiar responsable</h2><div className="mt-3 flex gap-2"><Button variant={mode === 'team' ? 'default' : 'outline'} size="sm" onClick={() => setMode('team')}>Equipo de Catastro</Button><Button variant={mode === 'other' ? 'default' : 'outline'} size="sm" onClick={() => setMode('other')}>Otro</Button></div>{mode === 'team' ? <Select className="mt-3" value={official} onChange={(event) => setOfficial(event.target.value)}><option value="">Selecciona un funcionario</option>{officials.map((value) => <option key={value.uid} value={value.uid}>{value.nombreCompleto}</option>)}</Select> : <Input className="mt-3" value={external} onChange={(event) => setExternal(event.target.value)} placeholder="Persona o dependencia"/>}<Button className="mt-3" disabled={assignee.isPending || (mode === 'team' ? !official : !external.trim())} onClick={() => assignee.mutate()}>Guardar responsable</Button></div><div><h2 className="font-semibold">Traslado por competencia</h2><Input className="mt-3" value={destination} onChange={(event) => setDestination(event.target.value)} placeholder="Dependencia competente"/><Button className="mt-3" variant="outline" disabled={!destination.trim() || transfer.isPending || item.estado !== 'En respuesta'} onClick={() => transfer.mutate()}>Trasladar expediente</Button><p className="mt-2 text-xs text-slate-500">Disponible desde “En respuesta”.</p></div><div><h2 className="font-semibold">Prioridad</h2><Select className="mt-3" value={item.prioridad ?? ''} onChange={(event) => priority.mutate(event.target.value as ExpedientPriority || undefined)}><option value="">Sin prioridad</option><option>Alta</option><option>Media</option><option>Baja</option></Select></div></div>)}
      {tab === 'Historial' && <div className="space-y-4"><h2 className="font-semibold">Historial completo</h2>{history.map((entry) => <article key={entry.id} className="border-l-2 border-primary/30 pl-4"><b className="text-sm">{entry.accion}</b><p className="text-sm text-slate-600">{entry.detalle}</p><small>{entry.usuario} · {entry.fecha?.toDate().toLocaleString('es-CO')}</small></article>)}</div>}
      {tab === 'Documentos' && <div className="py-6 text-center"><FileText className="mx-auto text-slate-400"/><p className="mt-2 text-sm text-slate-500">Documentos disponibles cuando se habilite Firebase Storage.</p></div>}</Card></section>
}
