import { useQuery } from '@tanstack/react-query'
import { Download, Printer } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Select } from '@/components/ui/select'
import { listExpedients, listHistoricalExpedients } from '@/services/expedient.service'
import type { Expedient } from '@/types/expedient'

function group(items: Expedient[], field: 'estado' | 'tipoTramite' | 'prioridad' | 'funcionarioAsignado' | 'predios') { return Object.entries(items.reduce<Record<string, number>>((result, item) => { const label = field === 'funcionarioAsignado' ? item.funcionarioAsignado?.nombreCompleto ?? item.responsableExterno ?? 'Sin asignar' : field === 'predios' ? item.predios[0]?.municipio ?? 'Sin municipio' : item[field] ?? 'Sin dato'; result[label] = (result[label] ?? 0) + 1; return result }, {})).sort((a, b) => b[1] - a[1]) }

export function ReportsPage() {
  const active = useQuery({ queryKey: ['expedients'], queryFn: listExpedients }); const closed = useQuery({ queryKey: ['historical-expedients'], queryFn: listHistoricalExpedients }); const [municipality, setMunicipality] = useState(''); const [status, setStatus] = useState(''); const [type, setType] = useState(''); const all = useMemo(() => [...(active.data ?? []), ...(closed.data ?? [])], [active.data, closed.data])
  const rows = useMemo(() => all.filter((item) => (!municipality || item.predios.some((property) => property.municipio === municipality)) && (!status || item.estado === status) && (!type || item.tipoTramite === type)), [all, municipality, status, type]); const municipalities = [...new Set(all.map((item) => item.predios[0]?.municipio).filter(Boolean))]; const exportExcel = () => { const header = 'Radicado,Estado,Tipo,Municipio,Responsable\n'; const csv = header + rows.map((item) => [item.numeroRadicado, item.estado, item.tipoTramite ?? '', item.predios[0]?.municipio ?? '', item.funcionarioAsignado?.nombreCompleto ?? item.responsableExterno ?? ''].map((value) => `"${value}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'reporte-sigecat.csv'; link.click(); URL.revokeObjectURL(url) }
  const kpis = [['Activos', rows.filter((item) => item.activo).length], ['Finalizados', rows.filter((item) => !item.activo).length], ['Vencidos', rows.filter((item) => item.estadoTermino === 'Vencido').length], ['Próximos a vencer', rows.filter((item) => item.estadoTermino === 'Próximo a vencer').length], ['Traslados', rows.filter((item) => item.trasladoPorCompetencia).length], ['Respuestas', rows.filter((item) => item.estado.includes('respuesta') || item.estado === 'Radicado de salida').length]]
  const Chart = ({ title, values }: { title: string; values: [string, number][] }) => <Card className="p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4 space-y-3">{values.map(([label, count]) => <button key={label} className="block w-full text-left" title={`${label}: ${count} expedientes`}><div className="flex justify-between text-sm"><span>{label}</span><b>{count}</b></div><div className="mt-1 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary transition-all hover:bg-primary/75" style={{ width: `${Math.max(5, count * 100 / Math.max(1, rows.length))}%` }}/></div></button>)}</div></Card>
  return <section className="mx-auto max-w-7xl space-y-6 print:p-0"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium text-primary">Análisis</p><h1 className="text-2xl font-semibold">Reportes</h1></div><div className="flex gap-2 print:hidden"><Button variant="outline" onClick={() => window.print()}><Printer size={16}/> PDF</Button><Button onClick={exportExcel}><Download size={16}/> Excel</Button></div></div><Card className="p-4 print:hidden"><div className="grid gap-3 md:grid-cols-3"><Select value={municipality} onChange={(event) => setMunicipality(event.target.value)}><option value="">Todos los municipios</option>{municipalities.map((value) => <option key={value}>{value}</option>)}</Select><Select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos los estados</option>{[...new Set(all.map((item) => item.estado))].map((value) => <option key={value}>{value}</option>)}</Select><Select value={type} onChange={(event) => setType(event.target.value)}><option value="">Todos los trámites</option>{[...new Set(all.map((item) => item.tipoTramite).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</Select></div></Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{kpis.map(([label, value]) => <Card key={label} className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></Card>)}</div><div className="grid gap-5 lg:grid-cols-2"><Chart title="Expedientes por estado" values={group(rows, 'estado')}/><Chart title="Por tipo de trámite" values={group(rows, 'tipoTramite')}/><Chart title="Por municipio" values={group(rows, 'predios')}/><Chart title="Rendimiento del equipo" values={group(rows, 'funcionarioAsignado')}/></div></section>
}
